export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_USERS = 'GET_USERS'
export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_ORDERS = 'GET_ORDERS'
export const GET_DISCOUNTS = 'GET_DISCOUNTSTS'